### ISSUE TITLE
Increase Memory size

### ISSUE THREAD

**Issue by nterhoeven** [TBroTeam/TBro#60]
I got the following error

Maybe the easiest (not the prettiest) way to resolve this is to increase the memory limit in a script with
```
ini_set('memory_limit', '512M')
```

```
PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /share/tbro/TranscriptDB/webservices/listing/Features.php on line 48
```

**Comment by iimog** [comment]
Hi @nterhoeven thanks for reporting this issue. It is actually related to #59 
For large transcriptomes the sanity check if a transcript belongs to the organism/release combo needs to much memory (because it has to check a huge list of valid ids). Unfortunately, I do not have an easy fix in mind. I will make this check optional via configuration options in the next release. However, I am not happy with this solution and open for any better suggestions.
